//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HytorcLogistic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.demoYassistance = new HashSet<demoYassistance>();
        }
    
        public int Id { get; set; }
        public string companyName { get; set; }
        public string phone { get; set; }
        public string ext { get; set; }
        public string nameContact { get; set; }
        public string department { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string workCenter { get; set; }
        public int UsersId { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demoYassistance> demoYassistance { get; set; }
    }
}
