//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HytorcLogistic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public string bills_num { get; set; }
        public System.DateTime delivery_time { get; set; }
        public string contract_num { get; set; }
        public string invoice_num { get; set; }
        public System.DateTime creation_date { get; set; }
        public double total_without_taxes { get; set; }
        public double total_with_taxes { get; set; }
        public string comments { get; set; }
        public string payment_status { get; set; }
        public string commission_status { get; set; }
        public System.DateTime date_portal { get; set; }
        public int ClientsId { get; set; }
    }
}
