//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HytorcLogistic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int Id { get; set; }
        public int ClientsId { get; set; }
        public System.DateTime date { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string reason { get; set; }
        public string comments { get; set; }
        public string time_arrival { get; set; }
        public string effective_time { get; set; }
    }
}
